# Understand permissions
pid /tmp/nginx.pid;

events{}
http {

# Change temp dirs to work with rootless
client_body_temp_path /tmp/client_temp;
proxy_temp_path       /tmp/proxy_temp_path;
fastcgi_temp_path     /tmp/fastcgi_temp;
uwsgi_temp_path       /tmp/uwsgi_temp;
scgi_temp_path        /tmp/scgi_temp;

# Make website recognise filetypes
include /etc/nginx/mime.types;

server {

	listen 8080;
	server_name localhost;

    root /usr/share/nginx/html;

    location ~ ^/(login|signup)\.html {
        if ($args != "") {
            proxy_pass http://api:8090$uri?$args;
            break;
        }
        try_files $uri =404;
    }

	location / {
		index index.html;
	}

	# API requests, forward to C++ backend
	location /api/ {
		proxy_pass http://api:8090/api/;

        # Inform the backend that the request is coming from a user, not just nginx
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

}
}
