# Understand permissions
pid /tmp/nginx.pid;

events{}
http {

# Change temp dirs to work with rootless
client_body_temp_path /tmp/client_temp;
proxy_temp_path       /tmp/proxy_temp_path;
fastcgi_temp_path     /tmp/fastcgi_temp;
uwsgi_temp_path       /tmp/uwsgi_temp;
scgi_temp_path        /tmp/scgi_temp;

# Make website recognise filetypes
include /etc/nginx/mime.types;

server {

	listen 8080;
	server_name localhost;


	location / {
        root /usr/share/nginx/html;
		index index.html;
	}

	# API requests, forward to C++ backend
    # TODO: Expand to account for more languages
    # Should modify to make it more extensible in the event of new languages added
    # Not that I plan on supporting more languages, but just in case
    # It might be better to make absolutely everything backend based
    # It might be a good idea to have the language code set as a header instead of a path prefix to simplify logic
	location ~ ^/(api|en|ja)/ {
		proxy_pass http://api:8090;

        # Inform the backend that the request is coming from a user, not just nginx
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}
}
