version: '3'
services:
  nginx-frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network
  
  api:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
