services:
  nginx-frontend:
    container_name: blog-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - app-network
  
  api:
    container_name: blog-api
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - database/postgres.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
      - postgres-network

  db:
    container_name: blog-db
    build:
      context: ./database/
      dockerfile: Dockerfile
    restart: always
    env_file: 
      - database/postgres.env
    # volumes: # Remove for testing the init
    #   - pgdata:/var/lib/postgresql
    networks:
      - postgres-network

networks:
  app-network:
    driver: bridge
  postgres-network:
    driver: bridge

volumes:
  pgdata:
