services:
  nginx-frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - app-network
  
  api:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - postgres.env
    depends_on:
      - db
    networks:
      - app-network
      - postgres-network

  db:
    image: postgres:alpine
    restart: always
    env_file: 
      - postgres.env
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - postgres-network

networks:
  app-network:
    driver: bridge
  postgres-network:
    driver: bridge

volumes:
  pgdata:
